name: Omer Anson
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

title:             'The Ramblings Of A Coder'
#tagline:           'By Omer Anson'

# Google services
google_analytics: UA-92510576-1

# Enable maths
kramdown:
  math_engine: mathjax
